var textDistance = 68;
if (argument0 = 1 ){ draw_text(x,y+textDistance, "Strong Rock"); } 
if (argument0 = 2 ){ draw_text(x,y+textDistance, "Bigger Rock"); } 
if (argument0 = 3 ){ draw_text(x,y+textDistance, "Triple Shot"); }
if (argument0 = 4 ){ draw_text(x,y+textDistance, "Life Drain"); } 
if (argument0 = 5 ){ draw_text(x,y+textDistance, "Tsunami"); } 
if (argument0 = 6 ){ draw_text(x,y+textDistance, "Octashot"); } 
if (argument0 = 7 ){ draw_text(x,y+textDistance, "Time Skip"); } 
if (argument0 = 8 ){ draw_text(x,y+textDistance, "Meteor Shower"); } 
if (argument0 = 9 ){ draw_text(x,y+textDistance, "Sun Beam"); } 
if (argument0 = 10 ){ draw_text(x,y+textDistance, "Sword Rain"); } 
if (argument0 = 11 ){ draw_text(x,y+textDistance, "Lighting Bolt"); } 
if (argument0 = 12 ){ draw_text(x,y+textDistance, "Meteor"); } 
if (argument0 = 13 ){ draw_text(x,y+textDistance, "Spear"); } 
if (argument0 = 14 ){ draw_text(x,y+textDistance, "Heal"); } 
if (argument0 = 15 ){ draw_text(x,y+textDistance, "Charm"); } 
